### ISSUE TITLE
231023 16시 문제사항

### ISSUE THREAD

**Issue by CultureAddiction** [dlwns97/MIMD#1]
1. 텍스쳐 매핑 해결 방식: .obj 파일의 맨 위 line 2, 3지우기 (mtl 파일 불러오는 부분) 
obj 파일을 직접적으로 건드리는 것은 장기적으로 좋지 않음. 조치 필요.
건드리지 않으면 크래쉬. 

2. 회전 안 하는 문제
결과물이 회전을 안하는 상태로 출력됨. line 41, 42, 44를 볼 때, mesh가 회전하기 전에 텍스쳐 매핑이 된 것과 연관 있을 수 있음.

3. ply 파일 확인 필요
ply 파일에 동작하는지 확인 필요. 일단 구한 ply 모델이 대부분 텍스쳐맵 (.jpg)을 포함하지 않거나 메쉬 자체에 텍스쳐링이 된 경우라서 아직 못함. 일단 visnu의 경우에는 ply 파일 내부를 수정하지 않고도 크래쉬가 나진 않았지만 텍스쳐링도 되지 않았음.

**Comment by CultureAddiction** [comment]
push 하기 이전에 추가한 코드: 
line 21     
texture_path = "C:/Users/user/Desktop/Workspace/231023_objply/garuda-and-vishnu-ply/Garuda and Vishnu_0.jpg"

line 37
    # Texture Image
    texture_image = o3d.io.read_image(texture_path)
    mesh.textures = [texture_image]

line 55, 62 
    rotated_name = os.path.join("", f"rotated{rotation_angle}.png") // 이 부분은 "file_name" 부분이 오류를 내서 임의로 삭제함. 바꿀 필요는 없음.

**Comment by CultureAddiction** [comment]
회전 안 하는 문제는 teexturing과 관계 없는 것 같음. 기존 코드는 회전하는지 확인 필요.

**Comment by CultureAddiction** [comment]
2번 문제 >>> 17시에 해결해서 push 함.

원본 코드 (rotated_model.py) 에서도 모델이 회전하는 것 같지 않음. 
두개의 mesh를 만들고 두개의 viewer을 만들어서 실행 중에도 한눈에 출력될 두 모델을 비교 가능하게 했음.
ctr.rotate 등의 코드는 지웠음. 
코드가 더러우니 약간의 개량 여지가 있음.
초반에 mesh.rotate에 np.pi (180도) 말고 처음 인수 rotation_angle을 참조하게끔 함

**Comment by dlwns97** [comment]
코드 내가 다시 만져서 반영할게

**Comment by CultureAddiction** [comment]
1 문제도 ISSUE 2 탭에 어느정도 해결되었으니 close 함.
